[General]
OutputAPI                            = d3d11_fl10_1
FullScreenMode                       = false

[GeneralExt]
FPSLimit                             = 20

[Glide]
VideoCard                           = voodoo_graphics
OnboardRAM                          = 2
MemorySizeOfTMU                     = 2048
NumberOfTMUs                        = 1
TMUFiltering                        = bilinear
Resolution                          = 2x
Antialiasing                        = appdriven
ForceVerticalSync                   = false
3DfxWatermark                       = false
3DfxSplashScreen                    = false
EnableInactiveAppState              = true
